INSERT INTO articulos (tipo, marca, peso, calidad, precio, proveedor_id, stock) VALUES
('Pañal', 'Huggies', 0.15, 'Alta', 10.00, 1, true),
('Pañal', 'Pampers', 0.14, 'Alta', 9.50, 1, true),
('Chupete', 'Philips Avent', 0.05, 'Alta', 5.00, 2, true),
('Chupete', 'Nuk', 0.04, 'Media', 4.00, 2, true),
('Ropa de bebé', 'Carter’s', 0.20, 'Alta', 25.00, 3, true),
('Ropa de bebé', 'Gerber', 0.18, 'Media', 20.00, 3, true),
('Juguete', 'Fisher-Price', 0.30, 'Alta', 15.00, 4, true),
('Juguete', 'VTech', 0.35, 'Media', 12.00, 4, true),
('Toallitas húmedas', 'Huggies', 0.25, 'Alta', 7.00, 5, true),
('Toallitas húmedas', 'Pampers', 0.20, 'Media', 6.50, 5, true),
('Biberón', 'Philips Avent', 0.10, 'Alta', 8.00, 6, true),
('Biberón', 'Dr. Brown’s', 0.12, 'Media', 9.00, 6, true),
('Silla de auto', 'Chicco', 3.50, 'Alta', 150.00, 7, true),
('Silla de auto', 'Graco', 3.00, 'Media', 120.00, 7, true),
('Cuna', 'Ikea', 15.00, 'Alta', 300.00, 8, true),
('Cuna', 'Dream On Me', 10.00, 'Media', 250.00, 8, true),
('Móvil para cuna', 'Fisher-Price', 0.50, 'Alta', 30.00, 9, true),
('Móvil para cuna', 'Tiny Love', 0.55, 'Media', 25.00, 9, true),
('Ropa de cama', 'Burt’s Bees', 1.00, 'Alta', 40.00, 10, true),
('Ropa de cama', 'Lambs & Ivy', 1.50, 'Media', 35.00, 10, true);

INSERT INTO proveedores (nombre, apellido, empresa, direccion) VALUES
('Laura', 'Fernández', 'Distribuciones de Bebés S.A.', 'Av. del Bebé 123'),
('Miguel', 'García', 'Pañales y Más', 'Calle de los Niños 456'),
('Sofia', 'Martínez', 'Artículos Infantiles', 'Calle de los Juguetes 789'),
('Juan', 'Pérez', 'Ropa de Bebé Co.', 'Paseo de la Infancia 101'),
('Clara', 'López', 'Todo para Bebés', 'Av. Lactancia 202'),
('Carlos', 'Sánchez', 'Sillas de Auto S.A.', 'Calle de la Seguridad 303'),
('Analia', 'Gómez', 'Móviles y Juguetes', 'Calle de los Sueños 404'),
('David', 'Ruiz', 'Cunas y Más', 'Calle de las Estrellas 505'),
('Elena', 'Ramírez', 'Distribuidora de Pañales', 'Av. de los Peques 606'),
('Roberto', 'Torres', 'Accesorios para Bebés', 'Calle de la Alegría 707');

INSERT INTO clientes (nombre, apellido, direccion) VALUES
('María', 'Hernández', 'Calle del Sol 1'),
('José', 'Martínez', 'Avenida del Mar 2'),
('Laura', 'González', 'Calle de la Luna 3'),
('Luis', 'Pérez', 'Calle de la Esperanza 4'),
('Anais', 'Sánchez', 'Avenida de la Paz 5'),
('Carmen', 'López', 'Calle de la Amistad 6'),
('Javier', 'Fernández', 'Calle de la Familia 7'),
('Claudia', 'Ramírez', 'Avenida de la Felicidad 8'),
('Diego', 'Torres', 'Calle de la Libertad 9'),
('Patricia', 'García', 'Calle de la Unidad 10'),
('Sergio', 'Morales', 'Calle de la Alegría 11'),
('Isabel', 'Díaz', 'Avenida de la Salud 12'),
('Fernando', 'Rojas', 'Calle del Recuerdo 13'),
('Verónica', 'Cruz', 'Calle de la Esperanza 14'),
('Raúl', 'Vásquez', 'Calle de la Inspiración 15'),
('Natalia', 'Martínez', 'Avenida de la Naturaleza 16'),
('Andrés', 'Mendoza', 'Calle de la Creatividad 17'),
('Lucía', 'Salazar', 'Calle de la Amabilidad 18'),
('Gabriel', 'Jiménez', 'Avenida de la Familia 19'),
('Victoria', 'Castillo', 'Calle del Futuro 20');